# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
SERVICES = {
  'server' => {
    ip: '192.168.56.110'
  },
}

Vagrant.configure("2") do |config|
  config.vm.box = "boxen/alpine-3.22"
  config.vm.box_version = "2025.08.20.12"  

  config.vm.define "hlahwaouS" do |hlahwaouS|
    hlahwaouS.vm.provider "virtualbox" do |vb|
      vb.memory = 1024 
      vb.cpus = 1 
      vb.name =  "hlahwaou_p2"
    end

    hlahwaouS.vm.hostname = "hlahwaouS"
    hlahwaouS.vm.network "private_network", ip: SERVICES['server'][:ip]

    hlahwaouS.vm.provision "shell", name: "setup-master", path: "scripts/setup_master.sh", args: [SERVICES['server'][:ip]]
    hlahwaouS.vm.provision "shell", name: "apply-mainfest", path: "scripts/apply_manifest.sh"
  
  end 
end

