# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
SERVICES = {
  'server' => {
    ip: '192.168.56.110'
  },
  'server_worker' => {
    ip: '192.168.56.111'
  }
}

Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/alpine-3.21"
  config.vm.box_version = "3.21.2-r0"
  
  config.vm.define "hlahwaouS" do |hlahwaouS|
    hlahwaouS.vm.provider "virtualbox" do |vb|
      vb.memory = 1024 
      vb.cpus = 1 
      vb.name =  "hlahwaou1"
    end

    hlahwaouS.vm.hostname = "hlahwaouS"
    hlahwaouS.vm.network "private_network", ip: SERVICES['server'][:ip]
    hlahwaouS.vm.synced_folder "conf", "/home/vagrant/conf", create: true

    hlahwaouS.vm.provision "shell", name: "setup-master", path: "scripts/setup_master.sh", args: [SERVICES['server'][:ip]]
  
  end 

  config.vm.define "hlahwaouSW" do |hlahwaouSW|
    hlahwaouSW.vm.provider "virtualbox" do |vb|
      vb.memory = 1024 
      vb.cpus = 1 
      vb.name =  "hlahwaou2"
    end 

    hlahwaouSW.vm.hostname = "hlahwaouSW"
    hlahwaouSW.vm.network "private_network", ip: SERVICES['server_worker'][:ip]
    hlahwaouSW.vm.synced_folder "conf", "/home/vagrant/conf", create: true

    hlahwaouSW.vm.provision "shell", name: "setup-agent", path: "scripts/setup_agent.sh", args: [SERVICES['server'][:ip], SERVICES['server_worker'][:ip]]

  end
end

