# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
SERVICES = {
  'server' => {
    ip: '192.168.56.110'
  },
  'server_worker' => {
    ip: '192.168.56.111'
  }
}
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20211001.0.5"

  config.vm.define "hlahwaouS" do  |hlahwaouS|
    hlahwaouS.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1 
      vb.name =  "hlahwaou1"
    end
    
    hlahwaouS.vm.hostname = "hlahwaouS"
    hlahwaouS.vm.network "private_network", ip: SERVICES['server'][:ip]
    
    hlahwaouS.vm.provision "shell", name: "install-k3s-server", inline: <<-SHELL
      sudo apt update 
      sudo apt upgrade -y
      sudo systemctl disable ufw
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip=192.168.56.110" sh - 
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip=192.168.56.110" K3S_TOKEN=12345 sh -s -
    SHELL
    end 

  config.vm.define "hlahwaouSW" do  |hlahwaouSW|
    hlahwaouSW.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1 
      vb.name =  "hlahwaou2"
    end 
    hlahwaouSW.vm.hostname = "hlahwaouSW"
    hlahwaouSW.vm.network "private_network", ip: SERVICES['server_worker'][:ip]
    hlahwaouSW.vm.provision "shell", name: "install-k3s-agent", inline: <<-SHELL
      sudo apt update 
      sudo apt upgrade -y
      sudo systemctl disable ufw
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=12345 sh -s - agent
    SHELL

  end
end
